spring.application.name=video-steam

server.port=8080
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=testtest
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=springboot

spring.datasource.url = jdbc:mysql://localhost:3306/roomdb
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
